In [ ]:

#--------------------TASK-1---------------------#
def battery_status(Charge):
  if Charge >70:
    status="High"
  elif Charge <=70 and Charge>50:
      status="Medium"
  else:
      status="Low"
  return status
battery_data=[
    {'Time':0,'Temperature':32,'Voltage':400,'Current':20,'Charge':95},
    {'Time':1,'Temperature':35,'Voltage':395,'Current':22,'Charge':88},
    {'Time':2,'Temperature':38,'Voltage':390,'Current':25,'Charge':80},
    {'Time':3,'Temperature':40,'Voltage':385,'Current':28,'Charge':70},
    {'Time':4,'Temperature':42,'Voltage':380,'Current':30,'Charge':60},
    {'Time':5,'Temperature':45,'Voltage':375,'Current':32,'Charge':48}
]
for i in battery_data:
  print(f"Time: {i["Time"]} , Temperature: {i["Temperature"]} , Voltage: {i["Voltage"]} , Current: {i["Current"]} , Charge: {i["Charge"]}")
  if i["Temperature"]>40 :
    print("High Temperature Alert!")
  else:
    print("Temperature Normal")
  if i["Charge"]<50 :
    print("Low Battery Alert!")
  else:
    print("Battery Charge Normal")
  status = battery_status(i["Charge"])
  print(f"Time: {i['Time']}, Charge: {i['Charge']}, Status: {status}")
  print("\n")



Time: 0 , Temperature: 32 , Voltage: 400 , Current: 20 , Charge: 95
Temperature Normal
Battery Charge Normal
Time: 0, Charge: 95, Status: High


Time: 1 , Temperature: 35 , Voltage: 395 , Current: 22 , Charge: 88
Temperature Normal
Battery Charge Normal
Time: 1, Charge: 88, Status: High


Time: 2 , Temperature: 38 , Voltage: 390 , Current: 25 , Charge: 80
Temperature Normal
Battery Charge Normal
Time: 2, Charge: 80, Status: High


Time: 3 , Temperature: 40 , Voltage: 385 , Current: 28 , Charge: 70
Temperature Normal
Battery Charge Normal
Time: 3, Charge: 70, Status: Medium


Time: 4 , Temperature: 42 , Voltage: 380 , Current: 30 , Charge: 60
High Temperature Alert!
Battery Charge Normal
Time: 4, Charge: 60, Status: Medium


Time: 5 , Temperature: 45 , Voltage: 375 , Current: 32 , Charge: 48
High Temperature Alert!
Low Battery Alert!
Time: 5, Charge: 48, Status: Low




In [ ]:
#-------------------TASK-2-------------------#
import numpy as np

battery_matrix = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
print(battery_matrix)
shape=np.shape(battery_matrix)
print(shape)
for i in range(shape[0]):
  average_temp=np.mean(battery_matrix[i,0])
  print(average_temp)

[[ 32 400  20  95]
 [ 35 395  22  88]
 [ 38 390  25  80]
 [ 40 385  28  70]
 [ 42 380  30  60]
 [ 45 375  32  48]]
(6, 4)
32.0
35.0
38.0
40.0
42.0
45.0


In [1]:
#--------------TASK-3------------------
import numpy as np
A = np.array([[2, 1], [1, 3]])
X = np.array([[40], [25]])
print("Matrix A:")
print(A)
print("\nVector X:")
print(X)
Y = np.dot(A, X)
print("\nResulting vector Y (Battery Stress Index):")
print(Y)
print("\n--- Additional Linear Algebra Tasks for Matrix A ---")
A_transpose = A.T
print("\nTranspose of A (A^T):")
print(A_transpose)
det_A = np.linalg.det(A)
print("\nDeterminant of A (det(A)):")
print(det_A)
if det_A != 0:
    A_inverse = np.linalg.inv(A)
    print("\nInverse of A (A^-1):")
    print(A_inverse)
else:
    print("\nInverse of A does not exist because the determinant is zero.")
print("\n--- Solving a System of Equations ---")
A_system = np.array([[2, 1], [1, 3]])
B_system = np.array([100, 120])
print("System Matrix A:")
print(A_system)
print("\nSystem Vector B:")
print(B_system)
X_solution = np.linalg.solve(A_system, B_system)
print("\nSolution for X (x, y):")
print(X_solution)
print(f"x = {X_solution[0]:.2f}")
print(f"y = {X_solution[1]:.2f}")

Matrix A:
[[2 1]
 [1 3]]

Vector X:
[[40]
 [25]]

Resulting vector Y (Battery Stress Index):
[[105]
 [115]]

--- Additional Linear Algebra Tasks for Matrix A ---

Transpose of A (A^T):
[[2 1]
 [1 3]]

Determinant of A (det(A)):
5.000000000000001

Inverse of A (A^-1):
[[ 0.6 -0.2]
 [-0.2  0.4]]

--- Solving a System of Equations ---
System Matrix A:
[[2 1]
 [1 3]]

System Vector B:
[100 120]

Solution for X (x, y):
[36. 28.]
x = 36.00
y = 28.00


In [2]:
#-----------------------TASK-4---------------------
import sympy as sp
t = sp.symbols('t')
C_t = 100 - 2*t - (1/2)*t**2
print(f"Battery charge function C(t): {C_t}")
dC_dt = sp.diff(C_t, t)
print(f"Rate of change of battery charge dC/dt: {dC_dt}")
discharge_rate_t2 = dC_dt.subs(t, 2)
print(f"Discharge rate at t = 2 hours (dC/dt at t=2): {discharge_rate_t2}")
discharge_rate_t5 = dC_dt.subs(t, 5)
print(f"Discharge rate at t = 5 hours (dC/dt at t=5): {discharge_rate_t5}")
if discharge_rate_t2 < discharge_rate_t5:
    interpretation = "The battery is losing charge at an increasing rate (the rate of change is becoming more negative)."
elif discharge_rate_t2 > discharge_rate_t5:
    interpretation = "The battery is losing charge at a decreasing rate (the rate of change is becoming less negative)."
else:
    interpretation = "The battery is losing charge at a constant rate."

print(interpretation)

Battery charge function C(t): -0.5*t**2 - 2*t + 100
Rate of change of battery charge dC/dt: -1.0*t - 2
Discharge rate at t = 2 hours (dC/dt at t=2): -4.00000000000000
Discharge rate at t = 5 hours (dC/dt at t=5): -7.00000000000000
The battery is losing charge at a decreasing rate (the rate of change is becoming less negative).
